### ISSUE TITLE
Initial selection not working

### ISSUE THREAD

**Issue by trentgu** [ClimberAB/ClimberSelectionBar#10]
I list from Year field: 2016, 2017
But when I set these initial data, it not working:

='2016'
=Year(Today())

I am using V3.1.3

**Comment by realej** [comment]
i had the same problem

**Comment by kfsjostrand** [comment]
I updated the extension with a fix for initial selections. Remember that calculated fields are not supported. If you used the expression editor Qlik Sense adds a "=" before the field name and treats the field as a calculated dimension. Remove the equal sign and it should work.
Since year is a number you should use it with out quotes.
=2016
=Year(Today())
I tried the above and they will work.
