### ISSUE TITLE
Date Range Selection changed after being applied (and extra stuff)

### ISSUE THREAD

**Issue by awolkovicz** [ClimberAB/ClimberSelectionBar#19]
Hi,

I set a date range like the following (please check that the min and max dates exist in the Date field):
![image](https://cloud.githubusercontent.com/assets/14092382/24808886/0c656e1e-1b94-11e7-9538-1b748ec7ac7d.png)

After I hit Apply I get the following:
![image](https://cloud.githubusercontent.com/assets/14092382/24809015/87f6d3c4-1b94-11e7-9599-5fc570646d33.png)

- Note that the date range changed from "01/03 to 31/03" to "02/03 to 01/04" everywhere, even though the selection was made correctly and accordingly to what I initially set.
- Note that, as mentioned above, there's data on the 01/03, and even though it's selected, the calendar says otherwise.
- Note that, there are no Dates in April, and yet 01/04 is available
- Related to the previous point, I noticed that for the "Date range min expression" and the "Date range max expression" I must set "=Min({1} Date) **- 1**" and "=Max({1} Date) **- 1**", instead of "=Min({1} Date)" and "=Max({1} Date)".
- Also, Why is that the data set must not have gaps? Is there a way of crossing out those Dates in the calendars?
- What does the red exclamation mark mean? (hovering says "Selection is not a range").
- Is there a way to customize the date format? (only for the date picker selector when the calendars and the date ranges are not displayed)

Thanks much in advance!

**Comment by mickeg** [comment]
Hi, 
This is probably caused by a time zone issue, we need more info to solve this.
Can you please attach a sample qvf?

//Mikael

**Comment by mickeg** [comment]
Attaching sample qvf from Agustin.

[Date Range.ZIP](https://github.com/ClimberAB/ClimberSelectionBar/files/930113/Date.Range.ZIP)

**Comment by awolkovicz** [comment]
Thanks! 😄

**Comment by ClimberExtensions** [comment]
@awolkovicz I've updated the extension, hopefully it will fix your problem that it selects the wrong dates. I think there was a bug related to UTC offset that caused the problem.
After update the about panel should say Version 1.1.8
![image](https://cloud.githubusercontent.com/assets/20192393/25149269/1a60a090-247e-11e7-8713-6586e2a5138b.png)
Thanks for sending us the sample app.
You are mixing date formats in your app and in your data. If you change the default date formats in the load script that would fix some problems you are experiencing.
![dateformats](https://cloud.githubusercontent.com/assets/20192393/25148779/62920220-247c-11e7-8ed5-74b362b0404b.PNG)
The default formats also is the date format that is displayed when you use the **default format** in Display date format. That should answers you question,
> Is there a way to customize the date format? 
![display format property](https://cloud.githubusercontent.com/assets/20192393/25148989/2cfadfd2-247d-11e7-8b24-13783afe99a9.PNG)
One other solution, if you want the M/D/YYYY format as in the supplied app, you can cast the date in the load script as a date instead.
![castasdate](https://cloud.githubusercontent.com/assets/20192393/25148788/6e77fb26-247c-11e7-9bad-f5c00642842a.PNG)

> Also, Why is that the data set must not have gaps? Is there a way of crossing out those Dates in the calendars?
> What does the red exclamation mark mean? (hovering says "Selection is not a range").
This is a date **range** picker, it make selections in a date range, from date to date. The exclamation mark is for information to the user that the selection is not a range and dates are missing inbetween, 
e.g 2016-01-01, 2016-01-02, 2016-01-03 is a range
e.g 2016-01-01,  2016-01-03 is not a range because 2016-01-02 is missing
Let us know if you still experience problems.

**Comment by awolkovicz** [comment]
Hi,

I downloaded the last version:
![image](https://cloud.githubusercontent.com/assets/14092382/25384140/874c98be-2995-11e7-8979-2ae358533f1e.png)

I applied the changes in the default date formats:
![image](https://cloud.githubusercontent.com/assets/14092382/25384161/a06e7128-2995-11e7-86b2-7397b42dea3a.png)

Also made sure to not to mix date formats when setting the Initial Selection and Min/Max dates:
![image](https://cloud.githubusercontent.com/assets/14092382/25385236/ca370fca-2999-11e7-83bc-27b03e2c08ca.png)

Also casted the date in the load statement:
![image](https://cloud.githubusercontent.com/assets/14092382/25384394/90011d9e-2996-11e7-9755-ad811df8bc23.png)

And still, when making a selection like the following:
![image](https://cloud.githubusercontent.com/assets/14092382/25384694/a741f216-2997-11e7-8735-54ecbe4e7bc4.png)

I still see wrong dates being displayed, even though the selection applied is correct:
![image](https://cloud.githubusercontent.com/assets/14092382/25385261/e14efd3a-2999-11e7-8c0e-e4fa4b833c79.png)

Regards,
Agu.-
