### ISSUE TITLE
Changing variable value does not update object

### ISSUE THREAD

**Issue by MostlyHarmless93907** [ClimberAB/ClimberSelectionBar#24]
I'm trying to use the variable option to set a dimension on a pie chart, but it doesn't seem to work.  I'm probably not doing something correctly, so any help would be appreciated.  Here's what I did:

Created variable vCustLevel and set its value to the dimension called GroupCustomer (also tried setting its initial value to nothing).
Placed ClimberSelectionBar on sheet and set it to Variable list type with values of Group, Sold To, Ship To.  Set the variable to vCustLevel.
Created expression for dimension in pie chart:  
If(vGroupCust = 'Group', GroupCustomer, if(vGroupCust = 'Sold To', SoldToCustomer, if(vGroupCust = 'Ship To', ShipToCustomer)))

The pie chart's dimension doesn't change when I change variable values in the ClimberSelectionBar.

Please advise.

Thank you.

Note:  I've tried various approaches in addition to the above and none have worked.  Tried setting dimension to =vCustLevel and assigning values to that variable based on selection in ClimberSelection bar, but nothing happens.

**Comment by ClimberExtensions** [comment]
This seems more like a generic Qlik Sense problem than an issue with the actual extension. Try first to see if you can make it work using the native variables. Post again if variables do not work for you in the extension. (For a quicker reply on Qlik Sense issues in general we recommend using QlikCommunity.)

**Comment by JohnnySix** [comment]
@sssimon-phoenix   -  would you be able to post what you did in order to make it work?  Same issue, am not sure why it doesn't pick up that the variable has changed.

**Comment by sssimon-phoenix** [comment]
I'm on vacation right now. I will try to find it or simulate it after. Or
you can try to do as I said. Variable, calculated dimension or metric must
not be based on simple conditions. If you add aggr function with some
calculation, you force qlik to recalculate and not use cache with. But with
larger dataset or weak machine this method will decrease performance and
GUI responsiveness.

Dne 14. 8. 2018 9:18 napsal uživatel "JohnnySix" <notifications@github.com>:

@sssimon-phoenix <https://github.com/sssimon-phoenix> - would you be able
to post what you did in order to make it work? Same issue, am not sure why
it doesn't pick up that the variable has changed.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ClimberAB/ClimberSelectionBar/issues/24#issuecomment-412778117>,
or mute the thread
