### ISSUE TITLE
Initial Selection is not working for the Fields

### ISSUE THREAD

**Issue by Lukassmo1207** [ClimberAB/ClimberSelectionBar#46]
### Description

Hi, 

I am trying to make an initital selection of the year "2017".

Also trying to initially select the dimension Version = "Budget". Please see the screenshots below.

Can somebody please explain in more details what kind of syntax is accepted by initital selection?

I was trying  =Year(Today()) but it didn't work.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/31701681/33656491-22270106-da6e-11e7-9985-0d5830c11de3.png)

![image](https://user-images.githubusercontent.com/31701681/33656537-4082351c-da6e-11e7-912e-b95e529109fe.png)

##### Expected behavior

[What you expected to happen]
![image](https://user-images.githubusercontent.com/31701681/33656296-8ffe4be0-da6d-11e7-8c04-82229df69f41.png)

##### Actual behavior

[What actually happened]
![image](https://user-images.githubusercontent.com/31701681/33656276-7de14278-da6d-11e7-8852-bb8666e4535b.png)

### Environment
```
I am using desktop version of Qlik Sense.
```
### Versions

* Extension version:
* Browser: Firefox
* Qlik Sense: June 2017
* Operating system: Windows 7
* [Other relevant versions]

**Comment by MichaelClimber** [comment]
From your description it seems you are doing it right. A bit confused about your "I am using cloud version of Qlik Seense" though. Extensions are not at all available in cloud yet so that can't be right?

Besides that we have not seen or been able to replicate this behavior. Things to try: Check the selection setting and chance them to "On Sheet" so it updates every time you switch sheets. Empty your browser cache to make sure you don't have an old version playing tricks with you. Check to make sure you have the latest version of the extension installed. 

One more thing that could potentially be wrong is if you are using the first June version. Qlik had a big bug in that version that made all extensions load very slowly. That could (thoretically) create some sort of mismatch in the timing of the selections. Please let us know how it goes,

**Comment by rbartley** [comment]
I found that the initial selection worked after opening up a new browser session after installing the extension.

**Comment by MichaelClimber** [comment]
Solved. Closing.
