### ISSUE TITLE
Work with locked field

### ISSUE THREAD

**Issue by kunstjan** [ClimberAB/ClimberSelectionBar#51]
### Description
Hello,
Thank you very much for your extension, it helpes us a lot in our work. I have two general questions and one small issue. 

1. Are you planning certification of your extension? Or is there any other guarantee that it will work with future updates of QS? 

2. I use your extension as the date range picker (don't know if it is relevant for the question)... When I have the used field locked, it still allows me to do the selection. Is this a bug or feature? Actually I like this, I just don't want to be surprised when it is "repaired" in some future version :-), so I rather ask :-)

3. Now the issue - when I use a locked field in the date range picker, the closed selection box shows the "No selection text", when I unlock the field in current selections, it shows the selected date range. Is it possible to show the selected date range also when the used field is locked?

### Steps to Reproduce

1. Create a list with Date range picker type
2. Add some date field
3. Do some selection in the field
4. Lock the selection

##### Expected behavior

Closed Date range picker should show the selected date range, for exampe 1.1.2018 - 14.2.2018

##### Actual behavior

Closed Date range picker shows the No selection text, for exampe "Select a date".

##### Operating system

```
[x] Windows
[ ] OSX
[ ] Linux
```
##### Qlik Sense

```
[x] Desktop
[ ] Enterprise
```

##### Browser

```
[ ] Chrome
[x] Firefox
[ ] Internet Explorer
[ ] Edge
[ ] Others: XXX
```

### Versions

* Extension version: 1.4
* Browser: 
* Qlik Sense: November 2017 Patch 2
* Operating system: Windows 10

**Comment by MichaelClimber** [comment]
Hi, 
and thank you for you input!
1. Yes, as soon as Qlik releases the details on how to certify extensions we will of course be interested in certifying our extensions. As of today only extensions created by Qlik employees have been certified. Do however note that we offer full support for all our extensions (including Plus-versions and the ones not on Branch) through a subscription. Contact us for more information on packages and pricing.
2. This is more of a missing feature on our end. I think we should support locked fields in a better way going forward but your comment is noted and we could potentially have "respect locked fields" as an option rather than a strict feature.
3. We should show the text also in a locked field. I will put that on our internal issue-list. Thanks for pointing it out.

I'm closing the issue but please feel free to reopen if you have additional questions.

Kind regards

Michael
