### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by eharz** [ClimberAB/ClimberSelectionBar#57]
**###Description**

Climber Selection Bar seems to be unable to identify one country - i.e. Bosnia and Herzegovina

##### Expected behavior
Flag of the country should be displayed

##### Actual behavior

Every other country is identified and its flag displayed besides the one of Bosnia and Herzegovina
### Environment
``
[X] Enterprise
```
### Versions

* Extension version: Climber Selection Bar 1.0.5.
* Browser: Google Chrome
* Qlik Sense server: 10.28.2.
* Operating system: Windows 10 Enterprise

### Screenshots

![b h_missing_flag](https://user-images.githubusercontent.com/29173386/37903901-fefdb0a2-30f9-11e8-8607-8bcc9a5f3bd9.PNG)

**Comment by edwardhallgren** [comment]
Hi,
In our flag mapping Bosnia and Herzegovina is "Bosnia-and-Herzegovina". So you can otherwise rename the country field in your data model or you can rename the flag file name in this path "cl-HorizontalSelectionBar\lib\images\flags". If you renaming it in the file name you need to do this everytime you're updating the extension. 

![image](https://user-images.githubusercontent.com/27728137/37907735-431b454a-3106-11e8-9854-628c0022f981.png)

Br
Edward

**Comment by eharz** [comment]
Hi Edward,

Thank you so much! :) I had tried every possible variation of that country's name, I guess I omitted that one...
Kind regards,
Nevena
