### ISSUE TITLE
Selection on generated autocalendar fields doesn´t allow to override the selection in set analysis

### ISSUE THREAD

**Issue by thkarner** [ClimberAB/ClimberSelectionBar#75]
### Description

[Description of the issue]
Selection on generated autocalendar fields doesn´t allow to override the selection in set analysis

### Steps to Reproduce

1. Load some fact data with the data manager wizard with a date field, e.g. [Sales Order Date] and a KPI, e.g. [Sales Revenue]
2. Autocalendar is automatically created
3. Create sheet with Climber Selection Bar extension with selection for years and months based on the derived calendar fields
Fields needs to be specified as =[Sales Order Date.autoCalendar.Year] and =[Sales Order Date.autoCalendar.Month]. If the equal sign is not provided, Climber selection bar doesn´t display anything.
4. Define a KPI "Sales Previous Month" with the following expression
SUM( {<[Sales Order Date.autoCalendar.MonthsAgo]={$(=Min([Sales Order Date.autoCalendar.MonthsAgo])+1)}, [Sales Order Date.autoCalendar.Month]=, [Sales Order Date.autoCalendar.Year]= >} [Sales Revenue])
5. Select e.g. June 2018 in Climber Selection bar only
6. In this case the expression for KPI "Sales Previous Month" shows 0, but it should show values for May 2018.
Only if the user selects June 2018 + May 2018 the correct result appears.

The following might be the reason for this behaviour:
- Current selection bar shows there is a selection on =[Sales Order Date.autoCalendar.Month]
- This selection can´t be overridden with set analysis [Sales Order Date.autoCalendar.Month]=
which causes showing the 0 value.
- If I use a filter pane instead to select a certain month the filter is applied on the field [Sales Order Date.autoCalendar.Month] directly and the value for previous month is shown.
- Probably if climber selection bar would use the real (derived) calendar field without the equal sign (like Qlik Sense Standard does), overriding of this selection in Set Analysis would be possible.

##### Expected behavior

[What you expected to happen]

##### Actual behavior

[What actually happened]

### Environment
```
[?] Desktop
[Yes] Enterprise
```
### Versions

* Extension version: 1.5.2
* Browser: Google Chrome
* Qlik Sense: Enterprise June 2018
* Operating system: Windows 7 (for testing)
* [Other relevant versions]

**Comment by Lojdquist** [comment]
Hi,

This bug is a Qlik bug, for autogenerated calendar fields, a field written like =[test date] vs test date, will be observed as two different selections for autogenerated calenders. The same behavior exists with Qliks filter pane, which can be seen below. We recommend creating your own calendar.

![autocalendarfield](https://user-images.githubusercontent.com/17699930/44136514-54a17c54-a06d-11e8-815c-c3f970ca1af6.png)

As for "If the equal sign is not provided, Climber selection bar doesn´t display anything.". You must remove the square brackets. However, because of the bug these fields won't reference to the same selections.

![climberselectionbar](https://user-images.githubusercontent.com/17699930/44137166-a895faa4-a06f-11e8-901e-213b7cb0b65f.png)
